### ISSUE TITLE
People who have crashes scripts

### ISSUE THREAD

**Issue by DynosaurRBE** [tyabus/xash3d#12]
There is new script is called the crash script that some uses it to their advantage to either boost their servers or eliminate their haters and rivals on the xash servers community, our server recently have been facing multiple attacks by some people who hate us, we contacted some people and they said use tyabus files but our server runs with temiz files so it doesn't work and converting it would take a long time and sacrifice some plugins such as (nademodes) which is important to our ze server, even if we did they also have more scripts such as (High ping script) also blocking their ip doesn't work because they keep on changing it and would also leads the server to straight death, this script have been around for long time but surprised no one talks about it, all what i am asking for is for xash devs to update their servers and make it more secure and safe environment for others creators to be creative and create their own server safely without any threats facing them, because this is cs1.6 the game we love, some can't afford pc to play it, that's why xash was an idea or ported in the first place.

**Comment by Mr0maks** [comment]
> There is new script is called the crash script that some uses it to their advantage to either boost their servers or eliminate their haters and rivals on the xash servers community, our server recently have been facing multiple attacks by some people who hate us, we contacted some people and they said use tyabus files but our server runs with temiz files so it doesn't work and converting it would take a long time and sacrifice some plugins such as (nademodes) which is important to our ze server, even if we did they also have more scripts such as (High ping script) also blocking their ip doesn't work because they keep on changing it and would also leads the server to straight death, this script have been around for long time but surprised no one talks about it, all what i am asking for is for xash devs to update their servers and make it more secure and safe environment for others creators to be creative and create their own server safely without any threats facing them, because this is cs1.6 the game we love, some can't afford pc to play it, that's why xash was an idea or ported in the first place.

What?
