### ISSUE TITLE
Bug touch

### ISSUE THREAD

**Issue by a1sbes** [tyabus/xash3d#13]
https://user-images.githubusercontent.com/94536394/171145274-7778d6a6-49a4-4865-913d-7722cac6751b.mp4

баг с тачем смена строн и тач профилем, кнопки которые на смене сторон не кликабельные есть переменые setcolor и все.

**Comment by Mr0maks** [comment]
Should be fixed now

**Comment by tyabus** [comment]
Tested latest https://github.com/tyabus/xash3d/commit/8b11220d9e52a5547e3e5fe27bd907e1b2a4e05c build, no longer happens.
