### ISSUE TITLE
Can't run xash build

### ISSUE THREAD

**Issue by ghost** [tyabus/xash3d#16]
Hello. I need your help. The assembly of xash does not start. I threw your assembly into usr/bin, but it still does not respond to the xashds -game cstrike command. Please help me solve this problem.
![Screenshot_20220802-181324_Termux](https://user-images.githubusercontent.com/110480429/182426965-42fff855-2c2b-4445-8ef9-6a6af6880ddb.jpg)

**Comment by AruMoon** [comment]
Install 32 bit libraries to your system

**Comment by AruMoon** [comment]
If you are on debian/ubuntu, install it `sudo apt install lib32gcc-s1`

**Comment by ghost** [comment]
I installed lib32gcc-s1, but the build still won't start.
![Screenshot_20220804-112511_Termux](https://user-images.githubusercontent.com/110480429/182808220-078f5da7-f0b7-4145-9f16-f6740e9cf920.jpg)

**Comment by AruMoon** [comment]
You don't have installed xashds
Download build from here to your server directory via `wget https://gitlab.com/tyabus/xash3d/-/jobs/2684303269/artifacts/raw/out2/engine/xash3d`
And run with `./xash3d -game cstrike`

**Comment by RED4ARK** [comment]
I did everything as you said. But now it says permission denied.
![Screenshot_20220804-135453_Termux](https://user-images.githubusercontent.com/110480429/182832438-ceba1c00-8b6e-44ba-9ef4-8eced55684cd.jpg)

**Comment by ghost** [comment]
The result is, here it is
![Screenshot_20220804-150021_Termux](https://user-images.githubusercontent.com/110480429/182842990-4a176b45-b594-4b19-aa5e-8c9edac064f5.jpg)

**Comment by AruMoon** [comment]
Close issue

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
I hope someone will help me sometime
