### ISSUE TITLE
Error when starting the build.

### ISSUE THREAD

**Issue by ghost** [tyabus/xash3d#17]
Hello. When using the xashds -game cstrike command, this error appears - Error: Unknown option -game. How do I fix it?
![Screenshot_20220806-234924_Termux](https://user-images.githubusercontent.com/110480429/183265798-d578798b-9746-47ec-982a-00408a5fefeb.jpg)
![Screenshot_20220806-234928_Termux](https://user-images.githubusercontent.com/110480429/183265810-57b415a5-ad71-4edc-8372-7f0e6269aa15.jpg)

**Comment by Czarintax** [comment]
You have to name your screen session.

**Comment by tyabus** [comment]
Learn basic computer knowledge then create issues here. You will be banned on next issue opening.
