### ISSUE TITLE
rename build to buildnum

### ISSUE THREAD

**Issue by hypeq** [tyabus/xash3d#2]
at 0.20 it has already been corrected, but it is worth it here too
p.s. tfc code conflict

**Comment by tyabus** [comment]
Already was fixed a long time ago in https://github.com/tyabus/xash3d/commit/45329545b0ec64453c23224fdc49f1357bea4ba3

About renaming, i'm not quite sure, even hlsdk-xash3d uses "build" cvar to determine if its xash3d or not.
