### ISSUE TITLE
[Request] Make a roadmap

### ISSUE THREAD

**Issue by xplshn** [tyabus/xash3d#22]
Make a roadmap in order to structure this project.
Define what it is about, make documentation and issues guides, so people know what will or not be taken into account, when they point out enhancements, feature requests, or encounter bugs.

**Comment by tyabus** [comment]
Hello and sorry for the long response time, there is no roadmap for this project.
Changes are usually accepted as long as they don't break compatibility with 0.19.2/0.19.3 clients and are useful.

As for the issue templates, they were added in 056b3904c5f0fc75e0a941a2dd4c418503a78d8e.

Closing as not planned for now.
