### ISSUE TITLE
xashds crash problem

### ISSUE THREAD

**Issue by gknn053** [tyabus/xash3d#24]
After starting the server everything works fine. But after changing the map, the server crashes when the player leaves the server. I have this problem only with this engine.

(xash3d.sh engine has no write permission)

**Comment by Troll338cz** [comment]
Are you sure this is related to engine itself? I did a test build and couldnt replicate it.
Its most likely server library. Try running the engine inside GDB to get a stacktrace it will show some info.

**Comment by gknn053** [comment]
The problem is caused by amxmodx (1.8.3) that I installed on the server.
When I install xash amxmodx (1.8.2) which I found from a source, it works fine.

Engine 0.20 amxmodx 1.8.3 runs fine, is it incompatible with this engine?

**Comment by Troll338cz** [comment]
It depends on binaries you used 1.8.2, 1.8.3, 1.9.0 work, you can even build 1.10 from here https://github.com/czarintax/amxmodx
