### ISSUE TITLE
Where Xash3d 0.19.4

### ISSUE THREAD

**Issue by LithuanianBoi40** [tyabus/xash3d#27]
**Is your feature request related to a problem? Please describe.**
A description of what the problem is. E.g: I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want us to add/improve/etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by LithuanianBoi40** [comment]
Please release 0.19.4 to github

**Comment by niqixash** [comment]
> Please release 0.19.4 to github

https://gitlab.com/tyabus/xash3d/-/pipelines

**Comment by tyabus** [comment]
We don't have a planned release just yet, but we do have autobuilds on GitLab!
https://gitlab.com/tyabus/xash3d/-/pipelines
