### ISSUE TITLE
xash security problem

### ISSUE THREAD

**Issue by gknn053** [tyabus/xash3d#28]
This server attacks other people's main servers, stealing and modifying their information:
OLD SCHOOL XG - PUB

**Comment by tyabus** [comment]
First of all, you are a known cheater and we do not handle this kind of issues here.

**Comment by gknn053** [comment]
Is it cheating to play on the computer? Then tell a1batross why win32 compilations are released

**Comment by XashWTR** [comment]
Seriously hes not hacking and hes have a server and hes playing with desktop , Someone called  Justtahsin.asm does it all.

**Comment by XashWTR** [comment]
![image-2](https://github.com/tyabus/xash3d/assets/167638285/20cfd4d6-c57c-4251-83f8-06b30a48766c)
![Screenshot_20240420-194838_Discord](https://github.com/tyabus/xash3d/assets/167638285/dbf2dc41-6ade-40b9-a1c6-34f0c142e359)
Here proofs What did you do to the game? Tahsin: I am transferring files that crash the game of anyone who opens the server list. Everyone's ip comes to me

**Comment by gknn053** [comment]
> First of all, you are a known cheater and we do not handle this kind of issues here.

Instead of calling me a cheater, first improve your security systems, no one's information safe. You said that you should have written the names of the people who showed the bots in the list, and the server I wrote about was doing this recently. https://github.com/tyabus/xash3d/issues/26#issuecomment-1902559697

It's you contradict yourself, pity.

**Comment by XashWTR** [comment]
> Öncelikle siz bilinen bir hilecisiniz ve burada bu tür konularla ilgilenmiyoruz.

Answer ?

**Comment by tyabus** [comment]
No arguing in issues. Closing this for contributors only.
