### ISSUE TITLE
Problem on building

### ISSUE THREAD

**Issue by bhmintz** [tyabus/xash3d#5]
-- Target architecture: i386
-- Building for 32 Bit
-- Target architecture: i386
-- Disabled PIE for xashmenu
-- <FindVGUI.cmake> ../hlsdk
-- </FindVGUI.cmake> /home/arturo/xash3d/hlsdk/linux/vgui.so
-- Disabled PIE for vgui_support
-- <FindSDL2.cmake> 
CMake Error at cmake/FindSDL2.cmake:107 (message):
  sdl2-config --libs returned code No such file or directory.  Check that
  sdl2-config is working.
Call Stack (most recent call first):
  cmake/FWGSLib.cmake:223 (find_package)
  cmake/FWGSLib.cmake:320 (fwgs_library_dependency)
  game_launch/CMakeLists.txt:40 (xash_link_sdl2)

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2.cmake:179 (find_package_handle_standard_args)
  cmake/FWGSLib.cmake:223 (find_package)
  cmake/FWGSLib.cmake:320 (fwgs_library_dependency)
  game_launch/CMakeLists.txt:40 (xash_link_sdl2)

That appears in the terminal. What am I doing wrong?

**Comment by tyabus** [comment]
libSDL2-dev:i386 package isn't installed. (if you are using deb based distro)
If you want to build 64bit build, pass -DXASH_64BIT=1.
Refer to https://github.com/FWGS/xash3d/wiki/Building-and-running#cmake-recommended.

**Comment by tyabus** [comment]
Closing due absence of activity.
