### ISSUE TITLE
A name for our fork

### ISSUE THREAD

**Issue by tyabus** [tyabus/xash3d#6]
I couldn't come up with somewhat decent name for our fork, so, i've decided to create issue to see if anyone can suggest anything decent.

**Comment by Czarintax** [comment]
### xashed

**Comment by hypeq** [comment]
isis3d

**Comment by klaymen1n** [comment]
Hach7j

**Comment by a1sbes** [comment]
NewXash, justXash, BFXash, iXash

**Comment by DeltaLima** [comment]
analog to Xash3D-FWGS you can call this fork just Xash3D-Tyabus :)

**Comment by tyabus** [comment]
> analog to Xash3D-FWGS you can call this fork just Xash3D-Tyabus :)

Nope, im not the only one working on this project

**Comment by hypeq** [comment]
sirya3d

**Comment by hypeq** [comment]
syria3d

**Comment by hypeq** [comment]
tyabus_puknul3d

**Comment by tyabus** [comment]
I will probably name this as "xash3d-ng"

**Comment by a1batross** [comment]
@tyabus but it's not an "-ng"?

**Comment by tyabus** [comment]
> @tyabus but it's not an "-ng"?

I know that 0.20 is technically the next generation, but i (and other people as well) couldn't come up with a somewhat reasonable naming for months (or maybe i was too picky?), and i can reason this naming by just saying that it's a next generation of 0.19 codebase... so...?

**Comment by a1batross** [comment]
@tyabus it's just a bit misleading. "Next Generation" vs "New Engine"...?

I have no examples when the old codebase was forked and maintained separately, so I don't know what would be better here. Still, recommending and calling your fork as "that tyabus's old engine fork" is incorrect too.

Well, what if it will be the opposite, i.e. adding "-og" instead? :)

**Comment by DeltaLima** [comment]
I like the "-og" proposal :)
