### ISSUE TITLE
MainUI, Server dosen't load at all

### ISSUE THREAD

**Issue by tyabus** [tyabus/xash3d#9]

**Comment by RED4ARK** [comment]
Hello, tyabus. I can imagine. I say right away, I threw your assembly into usr/bin.
![Screenshot_20220804-150021_Termux](https://user-images.githubusercontent.com/110480429/182934238-dc689a95-37ed-42a3-b9a3-602b390c28be.jpg)

**Comment by tyabus** [comment]
Fixed in https://github.com/tyabus/xash3d-android-project/commit/de32b0a6b1e7a187264466a1803a96d0d5eaee16
